# Generated by Django 4.2.7 on 2024-12-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0011_user_role_map_site_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuMaster',
        ),
        migrations.DeleteModel(
            name='RoleMenuMaster',
        ),
        migrations.DeleteModel(
            name='UserMenuDetails',
        ),
    ]
