# Generated by Django 4.2.7 on 2024-10-04 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Notification', '0003_alter_notification_log_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_notification_log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_id', models.TextField(blank=True, null=True)),
                ('shift_id', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('noti_send_time', models.DateTimeField(blank=True, null=True)),
                ('noti_click_time', models.DateTimeField(blank=True, null=True)),
                ('noti_opened_time', models.DateTimeField(blank=True, null=True)),
                ('booking_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_noti_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_notification_log',
            },
        ),
    ]
