# Generated by Django 4.2.7 on 2024-10-29 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0051_userslotdetails_site_id'),
        ('Notification', '0004_user_notification_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification_log',
            name='sc_roster_id',
        ),
        migrations.AddField(
            model_name='notification_log',
            name='slot_id',
            field=models.ForeignKey(blank=True, db_column='slot_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_notification_id', to='Masters.slotdetails'),
        ),
    ]
