# Generated by Django 4.2.7 on 2024-10-30 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0055_citymaster_state_id'),
        ('Notification', '0005_remove_notification_log_sc_roster_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification_log',
            name='slot_id',
        ),
        migrations.RemoveField(
            model_name='user_notification_log',
            name='shift_id',
        ),
        migrations.AddField(
            model_name='user_notification_log',
            name='employee_id',
            field=models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_notification_id', to='Masters.parameter_master'),
        ),
        migrations.AlterField(
            model_name='user_notification_log',
            name='slot_id',
            field=models.ForeignKey(blank=True, db_column='slot_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_notification_id', to='Masters.slotdetails'),
        ),
        migrations.AlterField(
            model_name='user_notification_log',
            name='type',
            field=models.ForeignKey(blank=True, db_column='type_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_noti_id_parameter', to='Masters.parameter_master'),
        ),
    ]
