# Generated by Django 4.2.7 on 2024-10-30 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0007_user_notification_log_notification_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_notification_log',
            name='employee_id',
        ),
    ]
