# Generated by Django 4.2.7 on 2024-10-30 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0055_citymaster_state_id'),
        ('Notification', '0008_remove_user_notification_log_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_notification_log',
            name='employee_id',
            field=models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_notif_id', to='Masters.sc_employee_master'),
        ),
    ]
