# Generated by Django 4.2.7 on 2024-11-07 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0057_userslotdetails_emp_id'),
        ('Notification', '0009_user_notification_log_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_notification_log',
            name='noti_opened_time',
        ),
        migrations.AddField(
            model_name='user_notification_log',
            name='emp_id',
            field=models.ForeignKey(blank=True, db_column='emp_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_notif_id', to='Masters.sc_employee_master'),
        ),
        migrations.AlterField(
            model_name='user_notification_log',
            name='employee_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
