# Generated by Django 4.2.7 on 2024-11-07 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Notification', '0010_remove_user_notification_log_noti_opened_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_notification_log',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user_notification_log',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_noti_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
