# Generated by Django 4.2.7 on 2024-11-07 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0011_user_notification_log_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_notification_log',
            old_name='booking_time',
            new_name='noti_opened_time',
        ),
        migrations.RenameField(
            model_name='user_notification_log',
            old_name='noti_click_time',
            new_name='noti_receive_time',
        ),
    ]
