# Generated by Django 4.2.7 on 2024-11-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0012_rename_booking_time_user_notification_log_noti_opened_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_notification_log',
            old_name='noti_opened_time',
            new_name='noti_click_time',
        ),
    ]
