# Generated by Django 4.2.7 on 2024-11-28 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0059_delete_pooldetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Notification', '0013_rename_noti_opened_time_user_notification_log_noti_click_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='slot_notifiaction_log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('noti_sent_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_noti_created_by', to=settings.AUTH_USER_MODEL)),
                ('slot_id', models.ForeignKey(blank=True, db_column='slot_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_notifi_id', to='Masters.slotdetails')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_noti_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'slot_notification_log',
            },
        ),
    ]
