# Generated by Django 4.2.7 on 2024-09-17 06:28

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0015_alter_sc_roster_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_master',
            name='company_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
