# Generated by Django 4.2.7 on 2024-10-04 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Masters', '0019_remove_application_search_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sc_employee_master',
            name='account_holder_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sc_employee_master',
            name='account_no',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sc_employee_master',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sc_employee_master',
            name='bank_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sc_employee_master',
            name='branch_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sc_employee_master',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sc_employee_master',
            name='company_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sc_employee_master',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sc_employee_master',
            name='esic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sc_employee_master',
            name='gender',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='sc_employee_master',
            name='handicapped',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='sc_employee_master',
            name='isfc_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sc_employee_master',
            name='pf_no',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sc_employee_master',
            name='pincode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sc_employee_master',
            name='state',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sc_employee_master',
            name='uan_no',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PoolDetails',
            fields=[
                ('pool_id', models.AutoField(primary_key=True, serialize=False)),
                ('pool_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pool_description', models.CharField(blank=True, max_length=200, null=True)),
                ('pool_status', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pool_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pool_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pool_details',
            },
        ),
    ]
