# Generated by Django 4.2.7 on 2024-10-04 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Masters', '0020_sc_employee_master_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sc_employee_master',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_relation', to='Masters.company_master'),
        ),
        migrations.CreateModel(
            name='SlotDetails',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('worksite', models.TextField(blank=True, null=True)),
                ('slot_name', models.BooleanField(blank=True, default=True, null=True)),
                ('slot_description', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_relation', to='Masters.company_master')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'slot_details',
            },
        ),
        migrations.CreateModel(
            name='ShiftDetails',
            fields=[
                ('shift_id', models.AutoField(primary_key=True, serialize=False)),
                ('shift_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('start_time', models.TextField(blank=True, null=True)),
                ('end_time', models.TextField(blank=True, null=True)),
                ('night_shift', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_created', to=settings.AUTH_USER_MODEL)),
                ('slot_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_relation', to='Masters.slotdetails')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shift_details',
            },
        ),
        migrations.CreateModel(
            name='SettingMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('noti_start_time', models.TextField(blank=True, null=True)),
                ('noti_end_time', models.TextField(blank=True, null=True)),
                ('no_of_notification', models.IntegerField(null=True)),
                ('interval', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setting_created', to=settings.AUTH_USER_MODEL)),
                ('slot_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setting_relation', to='Masters.slotdetails')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setting_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'setting_master',
            },
        ),
    ]
