# Generated by Django 4.2.7 on 2024-10-04 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0021_alter_sc_employee_master_company_id_slotdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingmaster',
            name='slot_id',
            field=models.ForeignKey(blank=True, db_column='slot_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setting_relation', to='Masters.slotdetails'),
        ),
        migrations.AlterField(
            model_name='shiftdetails',
            name='slot_id',
            field=models.ForeignKey(blank=True, db_column='slot_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_relation', to='Masters.slotdetails'),
        ),
    ]
