# Generated by Django 4.2.7 on 2024-10-04 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Masters', '0022_alter_settingmaster_slot_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShiftDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.TextField(blank=True, null=True)),
                ('slot_id', models.TextField(blank=True, null=True)),
                ('shift_id', models.TextField(blank=True, null=True)),
                ('confirmation', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_shit_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_shift_details',
            },
        ),
    ]
