# Generated by Django 4.2.7 on 2024-10-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0023_usershiftdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state_id', models.IntegerField(null=True)),
                ('state_name', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('state_status', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'tbl_state_master',
            },
        ),
    ]
