# Generated by Django 4.2.7 on 2024-10-04 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0024_statemaster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sc_employee_master',
            old_name='isfc_code',
            new_name='ifsc_code',
        ),
    ]
