# Generated by Django 4.2.7 on 2024-10-04 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0025_rename_isfc_code_sc_employee_master_ifsc_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sc_employee_master',
            name='company_id',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_relation', to='Masters.company_master'),
        ),
    ]
