# Generated by Django 4.2.7 on 2024-10-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0026_alter_sc_employee_master_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotdetails',
            name='slot_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
