# Generated by Django 4.2.7 on 2024-10-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0028_alter_sc_employee_master_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftdetails',
            name='shift_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
