# Generated by Django 4.2.7 on 2024-10-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0029_alter_shiftdetails_shift_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingmaster',
            name='noti_end_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settingmaster',
            name='noti_start_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
