# Generated by Django 4.2.7 on 2024-10-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0030_alter_settingmaster_noti_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotdetails',
            name='end_time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slotdetails',
            name='night_shift',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='slotdetails',
            name='shift_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slotdetails',
            name='start_time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
