# Generated by Django 4.2.7 on 2024-10-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0032_remove_slotdetails_worksite_slotdetails_site_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingmaster',
            name='no_of_employee',
            field=models.IntegerField(null=True),
        ),
    ]
