# Generated by Django 4.2.7 on 2024-10-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0033_settingmaster_no_of_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotdetails',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
