# Generated by Django 4.2.7 on 2024-10-10 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0033_remove_sc_employee_master_worksite'),
    ]

    operations = [
        migrations.AddField(
            model_name='sc_employee_master',
            name='worksite',
            field=models.ForeignKey(blank=True, db_column='site_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_relation', to='Masters.site_master'),
        ),
    ]
