# Generated by Django 4.2.7 on 2024-10-10 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0003_slot_attendance_details'),
        ('Masters', '0034_sc_employee_master_worksite'),
    ]

    operations = [
        migrations.AddField(
            model_name='sc_employee_master',
            name='designation',
            field=models.ForeignKey(blank=True, db_column='designation_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designation_relation', to='Payroll.designation_master'),
        ),
    ]
