# Generated by Django 4.2.7 on 2024-10-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0034_slotdetails_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotdetails',
            name='messege',
            field=models.TextField(blank=True, null=True),
        ),
    ]
