# Generated by Django 4.2.7 on 2024-10-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0035_slotdetails_messege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotdetails',
            name='messege',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
