# Generated by Django 4.2.7 on 2024-10-10 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0003_slot_attendance_details'),
        ('Masters', '0035_sc_employee_master_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_designation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('state_status', models.BooleanField(blank=True, default=True, null=True)),
                ('designation_id', models.ForeignKey(blank=True, db_column='designation_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_designation_relation', to='Payroll.designation_master')),
                ('employee_id', models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_designation_relation', to='Masters.sc_employee_master')),
            ],
            options={
                'db_table': 'tbl_employee_designation',
            },
        ),
    ]
