# Generated by Django 4.2.7 on 2024-10-10 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0036_employee_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_site',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('state_status', models.BooleanField(blank=True, default=True, null=True)),
                ('employee_id', models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_site_relation', to='Masters.sc_employee_master')),
                ('site_id', models.ForeignKey(blank=True, db_column='site_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_site_relation', to='Masters.site_master')),
            ],
            options={
                'db_table': 'tbl_employee_site',
            },
        ),
    ]
