# Generated by Django 4.2.7 on 2024-10-18 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0033_slotdetails_designation_id'),
        ('Masters', '0036_alter_slotdetails_messege'),
    ]

    operations = [
    ]
