# Generated by Django 4.2.7 on 2024-10-17 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0010_alter_site_card_relation_unique_together_and_more'),
        ('Masters', '0036_alter_slotdetails_messege'),
    ]

    operations = [
        migrations.AddField(
            model_name='sc_employee_master',
            name='designation',
            field=models.ForeignKey(blank=True, db_column='designation_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designation_relation', to='Payroll.designation_master'),
        ),
    ]
