# Generated by Django 4.2.7 on 2024-10-18 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0033_remove_sc_employee_master_worksite'),
        ('Masters', '0037_merge_20241018_1310'),
    ]

    operations = [
    ]
