# Generated by Django 4.2.7 on 2024-10-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0037_employee_site'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee_designation',
            table='employee_designation',
        ),
        migrations.AlterModelTable(
            name='employee_site',
            table='employee_site',
        ),
    ]
