# Generated by Django 4.2.7 on 2024-10-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0038_alter_employee_designation_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_designation',
            name='employee_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee_site',
            name='employee_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
