# Generated by Django 4.2.7 on 2024-10-18 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0010_daily_salary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Masters', '0038_merge_20241018_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city_id', models.IntegerField(null=True)),
                ('city_name', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('state_status', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'tbl_city_master',
            },
        ),
        migrations.CreateModel(
            name='UserSlotDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.TextField(blank=True, null=True)),
                ('confirmation', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_shit_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_slot_details',
            },
        ),
        migrations.RenameField(
            model_name='slotdetails',
            old_name='messege',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='statemaster',
            name='state_id',
        ),
        migrations.AddField(
            model_name='sc_employee_master',
            name='designation',
            field=models.ForeignKey(blank=True, db_column='designation_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designation_relation', to='Payroll.designation_master'),
        ),
        migrations.AddField(
            model_name='sc_employee_master',
            name='worksite',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statemaster',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='UserShiftDetails',
        ),
        migrations.AddField(
            model_name='userslotdetails',
            name='slot_id',
            field=models.ForeignKey(blank=True, db_column='slot_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserSlotDetails_slot_id', to='Masters.slotdetails'),
        ),
    ]
