# Generated by Django 4.2.7 on 2024-10-18 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0039_citymaster_userslotdetails_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StateMaster',
        ),
    ]
