# Generated by Django 4.2.7 on 2024-10-18 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0039_alter_employee_designation_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sc_employee_master',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='sc_employee_master',
            name='worksite',
        ),
    ]
