# Generated by Django 4.2.7 on 2024-10-18 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0041_statemaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_master',
            name='city_id',
            field=models.ForeignKey(blank=True, db_column='city_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_master_city_id', to='Masters.citymaster'),
        ),
        migrations.AddField(
            model_name='site_master',
            name='state_id',
            field=models.ForeignKey(blank=True, db_column='state_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_master_site_master', to='Masters.statemaster'),
        ),
    ]
