# Generated by Django 4.2.7 on 2024-10-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0042_site_master_city_id_site_master_state_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='USERSHift',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.TextField(blank=True, null=True)),
                ('confirmation', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'user_shift',
            },
        ),
    ]
