# Generated by Django 4.2.7 on 2024-10-18 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0043_usershift'),
    ]

    operations = [
        migrations.DeleteModel(
            name='USERSHift',
        ),
    ]
