# Generated by Django 4.2.7 on 2024-10-18 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0044_delete_usershift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sc_employee_master',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='sc_employee_master',
            name='worksite',
        ),
    ]
