# Generated by Django 4.2.7 on 2024-10-22 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0045_remove_sc_employee_master_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sc_employee_master',
            name='state',
        ),
        migrations.AddField(
            model_name='sc_employee_master',
            name='state_id',
            field=models.ForeignKey(blank=True, db_column='state_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_relation_state_id', to='Masters.statemaster'),
        ),
    ]
