# Generated by Django 4.2.7 on 2024-10-25 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0041_employee_designation_company_id_and_more'),
        ('Masters', '0046_remove_sc_employee_master_state_and_more'),
    ]

    operations = [
    ]
