# Generated by Django 4.2.7 on 2024-10-25 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0047_merge_20241025_1046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShiftDetails',
        ),
    ]
