# Generated by Django 4.2.7 on 2024-10-25 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0046_userslotdetails_company_id'),
        ('Masters', '0048_delete_shiftdetails'),
    ]

    operations = [
    ]
