# Generated by Django 4.2.7 on 2024-10-25 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0049_merge_20241025_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userslotdetails',
            name='confirmation',
        ),
    ]
