# Generated by Django 4.2.7 on 2024-10-25 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0050_remove_userslotdetails_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userslotdetails',
            name='site_id',
            field=models.ForeignKey(blank=True, db_column='site_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserSlotDetails_site_id', to='Masters.site_master'),
        ),
    ]
