# Generated by Django 4.2.7 on 2024-10-29 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0052_citymaster_state_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citymaster',
            old_name='state_status',
            new_name='city_status',
        ),
    ]
