# Generated by Django 4.2.7 on 2024-10-29 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0053_rename_state_status_citymaster_city_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citymaster',
            name='state_id',
        ),
    ]
