# Generated by Django 4.2.7 on 2024-11-07 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Masters', '0057_userslotdetails_emp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistUserSlotDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('company_id', models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HistUserSlotDetails_company_id', to='Masters.company_master')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Hist_user_shit_created', to=settings.AUTH_USER_MODEL)),
                ('emp_id', models.ForeignKey(blank=True, db_column='emp_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HistUserSlotDetails_emp_id', to='Masters.sc_employee_master')),
                ('site_id', models.ForeignKey(blank=True, db_column='site_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HistUserSlotDetails_site_id', to='Masters.site_master')),
                ('slot_id', models.ForeignKey(blank=True, db_column='slot_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HistUserSlotDetails_slot_id', to='Masters.slotdetails')),
            ],
            options={
                'db_table': 'hist_user_slot_details',
            },
        ),
    ]
