# Generated by Django 4.2.7 on 2024-11-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0058_histuserslotdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PoolDetails',
        ),
    ]
