# Generated by Django 4.2.7 on 2024-11-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0059_delete_pooldetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingmaster',
            name='interval',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
