# Generated by Django 4.2.7 on 2024-12-11 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0042_payment_details_api_key_payment_details_secret_key'),
        ('Masters', '0061_slotdetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userslotdetails',
            name='status',
            field=models.ForeignKey(blank=True, db_column='status_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserSlotDetails_status_id', to='Payroll.statusmaster'),
        ),
    ]
