# Generated by Django 4.2.7 on 2024-12-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0062_userslotdetails_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_designation',
            name='state_status',
        ),
        migrations.RemoveField(
            model_name='employee_site',
            name='state_status',
        ),
        migrations.RemoveField(
            model_name='site_master',
            name='no_of_days',
        ),
        migrations.RemoveField(
            model_name='site_master',
            name='notification_time',
        ),
        migrations.RemoveField(
            model_name='site_master',
            name='reminder_time',
        ),
        migrations.RemoveField(
            model_name='site_master',
            name='roster_type',
        ),
    ]
