# Generated by Django 4.2.7 on 2025-01-08 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Masters', '0063_remove_employee_designation_state_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymaster',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='citymaster',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='citymaster',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='statemaster',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='statemaster',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='statemaster',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
