# Generated by Django 4.2.7 on 2025-02-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0065_rename_state_id_citymaster_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter_master',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
