# Generated by Django 4.2.7 on 2025-02-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0066_parameter_master_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter_master',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
