# Generated by Django 4.2.7 on 2025-05-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0067_alter_parameter_master_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter_master',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
