# Generated by Django 4.2.7 on 2025-01-08 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tax', '0002_alter_actmaster_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slab',
            name='slab_id',
            field=models.ForeignKey(blank=True, db_column='slab_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Tax.slabmaster'),
        ),
    ]
