# Generated by Django 4.2.7 on 2025-01-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tax', '0006_remove_slabmaster_lwf_applicable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slabmaster',
            name='slab_due_months',
        ),
    ]
