# Generated by Django 4.2.7 on 2025-01-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tax', '0008_slabmaster_act_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='slabmaster',
            name='slab_months_challan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
