# Generated by Django 4.2.7 on 2025-01-15 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tax', '0009_slabmaster_slab_months_challan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxcalculation',
            name='act',
            field=models.ForeignKey(blank=True, db_column='act_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_act', to='Tax.actmaster'),
        ),
    ]
