# Generated by Django 4.2.7 on 2025-01-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tax', '0012_alter_taxcalculation_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxcalculation',
            name='gross_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
