# Generated by Django 4.2.7 on 2025-01-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tax', '0013_alter_taxcalculation_gross_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxcalculation',
            name='tax_deducted',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
