# Generated by Django 4.2.7 on 2025-01-20 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tax', '0014_taxcalculation_tax_deducted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxcalculation',
            old_name='Employer_deduct',
            new_name='employer_deduct',
        ),
    ]
