# Generated by Django 4.2.7 on 2025-02-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tax', '0015_rename_employer_deduct_taxcalculation_employer_deduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxcalculation',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
