# Generated by Django 4.2.7 on 2024-10-07 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Masters', '0019_remove_application_search_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='rate_card_master',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_name', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_card_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rate_card_master',
            },
        ),
        migrations.CreateModel(
            name='site_card_relation',
            fields=[
                ('relation_id', models.AutoField(primary_key=True, serialize=False)),
                ('relation_name', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('card_id', models.ForeignKey(blank=True, db_column='card_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_card_master_id', to='Payroll.rate_card_master')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_role_card_created_by', to=settings.AUTH_USER_MODEL)),
                ('site_id', models.ForeignKey(blank=True, db_column='site_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_master_id', to='Masters.site_master')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_role_card_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'site_card_relation',
            },
        ),
        migrations.CreateModel(
            name='salary_element_master',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.TextField(blank=True, null=True)),
                ('pay_type', models.TextField(blank=True, null=True)),
                ('classification', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_item_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_item_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'salary_element_master',
            },
        ),
        migrations.CreateModel(
            name='RateCardSalaryElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.TextField(blank=True, null=True)),
                ('pay_type', models.TextField(blank=True, null=True)),
                ('classification', models.TextField(blank=True, null=True)),
                ('four_hour_amount', models.BigIntegerField(null=True)),
                ('nine_hour_amount', models.BigIntegerField(null=True)),
                ('rate_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Payroll.rate_card_master')),
                ('salary_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Payroll.salary_element_master')),
            ],
            options={
                'db_table': 'rate_card_salary_element',
            },
        ),
        migrations.AddField(
            model_name='rate_card_master',
            name='item_ids',
            field=models.ManyToManyField(blank=True, related_name='rate_cards', through='Payroll.RateCardSalaryElement', to='Payroll.salary_element_master'),
        ),
        migrations.AddField(
            model_name='rate_card_master',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_card_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='employee_rate_card_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.TextField(blank=True, null=True)),
                ('item_name', models.TextField(blank=True, null=True)),
                ('pay_type', models.TextField(blank=True, null=True)),
                ('classification', models.TextField(blank=True, null=True)),
                ('four_hour_amount', models.BigIntegerField(null=True)),
                ('nine_hour_amount', models.BigIntegerField(null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('card_id', models.ForeignKey(blank=True, db_column='card_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_card_id', to='Payroll.rate_card_master')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_rate_card_created_by', to=settings.AUTH_USER_MODEL)),
                ('item_id', models.ForeignKey(blank=True, db_column='item_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_rate_card_item_id', to='Payroll.salary_element_master')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_rate_card_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_rate_card_details',
            },
        ),
        migrations.CreateModel(
            name='designation_master',
            fields=[
                ('designation_id', models.AutoField(primary_key=True, serialize=False)),
                ('designation_name', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designation_master_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designation_master_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'designation_master',
            },
        ),
    ]
