# Generated by Django 4.2.7 on 2024-10-09 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_card_relation',
            name='designation_id',
            field=models.ForeignKey(blank=True, db_column='designation_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_designation_master', to='Payroll.designation_master'),
        ),
    ]
