# Generated by Django 4.2.7 on 2024-10-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0003_slot_attendance_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot_attendance_details',
            name='employee_id',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
