# Generated by Django 4.2.7 on 2024-10-11 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0006_alter_slot_attendance_details_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot_attendance_details',
            name='employee_id',
        ),
    ]
