# Generated by Django 4.2.7 on 2024-10-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0007_remove_slot_attendance_details_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot_attendance_details',
            name='employee_id',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
