# Generated by Django 4.2.7 on 2024-10-15 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0032_remove_slotdetails_worksite_slotdetails_site_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Payroll', '0008_slot_attendance_details_employee_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='site_card_relation',
            unique_together={('site_id', 'card_id', 'designation_id')},
        ),
        migrations.CreateModel(
            name='slot_employee_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.TextField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_employee_created_by', to=settings.AUTH_USER_MODEL)),
                ('slot_id', models.ForeignKey(blank=True, db_column='slot_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_slot_id', to='Masters.slotdetails')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_employee_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'slot_employee_details',
            },
        ),
    ]
