# Generated by Django 4.2.7 on 2024-10-18 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0039_citymaster_userslotdetails_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Payroll', '0010_daily_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_salary',
            name='company_id',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_salary_company_id', to='Masters.company_master'),
        ),
        migrations.AddField(
            model_name='slot_employee_details',
            name='company_id',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_employee_company_id', to='Masters.company_master'),
        ),
        migrations.CreateModel(
            name='salary_generated_log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.TextField(blank=True, max_length=250, null=True)),
                ('slot_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company_id', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='sal_gen_log_company_id', to='Masters.company_master')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sal_gen_log_created_by', to=settings.AUTH_USER_MODEL)),
                ('slot_id', models.ForeignKey(db_column='slot_id', on_delete=django.db.models.deletion.CASCADE, related_name='sal_gen_log_slot_id', to='Masters.slotdetails')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sal_gen_log_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='income_tax_deduction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.TextField(blank=True, max_length=250, null=True)),
                ('deduction_date', models.DateField(blank=True, null=True)),
                ('deduction_amount', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company_id', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='income_tax_deduction_company_id', to='Masters.company_master')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_tax_deduction_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_tax_deduction_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
