# Generated by Django 4.2.7 on 2024-10-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0011_daily_salary_company_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income_tax_deduction',
            name='deduction_date',
        ),
        migrations.AddField(
            model_name='income_tax_deduction',
            name='deduction_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='income_tax_deduction',
            name='deduction_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='income_tax_deduction',
            name='is_deducted',
            field=models.BooleanField(default=False),
        ),
    ]
