# Generated by Django 4.2.7 on 2024-10-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0013_alter_income_tax_deduction_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary_generated_log',
            name='slot_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
