# Generated by Django 4.2.7 on 2024-10-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0014_alter_salary_generated_log_slot_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot_attendance_details',
            name='attendance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
