# Generated by Django 4.2.7 on 2024-10-25 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Masters', '0046_userslotdetails_company_id'),
        ('Payroll', '0015_alter_slot_attendance_details_attendance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusMaster',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'status_master',
            },
        ),
        migrations.AddField(
            model_name='income_tax_deduction',
            name='deducted_on',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='PayoutDetails',
            fields=[
                ('payout_id', models.AutoField(primary_key=True, serialize=False)),
                ('razorpay_payout_id', models.CharField(blank=True, max_length=100, null=True)),
                ('fund_account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('utr', models.CharField(blank=True, max_length=100, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('payout_for_date', models.DateField(blank=True, null=True)),
                ('payment_initiated_date', models.DateTimeField(blank=True, null=True)),
                ('payment_completed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_company', to='Masters.company_master')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_employee', to='Masters.sc_employee_master')),
                ('payout_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_status', to='Payroll.statusmaster')),
                ('slot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_slot', to='Masters.slotdetails')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payout_details',
            },
        ),
    ]
