# Generated by Django 4.2.7 on 2024-10-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0016_statusmaster_income_tax_deduction_deducted_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot_attendance_details',
            name='attendance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
