# Generated by Django 4.2.7 on 2024-11-14 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0017_alter_slot_attendance_details_attendance_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary_element_master',
            old_name='classification',
            new_name='basis',
        ),
    ]
