# Generated by Django 4.2.7 on 2024-11-15 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0020_pay_type_basis_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary_element_master',
            name='basis',
            field=models.ForeignKey(blank=True, db_column='basis', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_basis_relation', to='Payroll.basis_type'),
        ),
        migrations.AlterField(
            model_name='salary_element_master',
            name='pay_type',
            field=models.ForeignKey(blank=True, db_column='pay_type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_pay_relation', to='Payroll.pay_type'),
        ),
    ]
