# Generated by Django 4.2.7 on 2024-11-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0021_alter_salary_element_master_basis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary_element_master',
            name='pay_type_new',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
