# Generated by Django 4.2.7 on 2024-11-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0022_alter_salary_element_master_pay_type_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary_element_master',
            name='pay_type_new',
            field=models.TextField(blank=True, null=True),
        ),
    ]
