# Generated by Django 4.2.7 on 2024-11-15 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0023_alter_salary_element_master_pay_type_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary_element_master',
            name='pay_type_new',
        ),
    ]
