# Generated by Django 4.2.7 on 2024-11-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0024_remove_salary_element_master_pay_type_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site_card_relation',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='site_card_relation',
            old_name='designation_id',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='site_card_relation',
            old_name='site_id',
            new_name='site',
        ),
    ]
