# Generated by Django 4.2.7 on 2024-11-19 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0026_alter_slot_attendance_details_attendance_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary_element_master',
            name='basis',
        ),
        migrations.AddField(
            model_name='salary_element_master',
            name='classification',
            field=models.ForeignKey(blank=True, db_column='classification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_basis_relation', to='Payroll.basis_type'),
        ),
    ]
