# Generated by Django 4.2.7 on 2024-11-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0027_remove_salary_element_master_basis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_salary',
            name='attendance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
