# Generated by Django 4.2.7 on 2024-11-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0028_alter_daily_salary_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratecardsalaryelement',
            name='four_hour_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ratecardsalaryelement',
            name='nine_hour_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
