# Generated by Django 4.2.7 on 2024-11-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0029_alter_ratecardsalaryelement_four_hour_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratecardsalaryelement',
            name='four_hour_amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ratecardsalaryelement',
            name='nine_hour_amount',
            field=models.BigIntegerField(null=True),
        ),
    ]
