# Generated by Django 4.2.7 on 2024-11-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0030_alter_ratecardsalaryelement_four_hour_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratecardsalaryelement',
            name='four_hour_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ratecardsalaryelement',
            name='nine_hour_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
