# Generated by Django 4.2.7 on 2024-12-02 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0032_statusmaster_status_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot_attendance_details',
            name='status',
            field=models.ForeignKey(blank=True, db_column='status_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_status', to='Payroll.statusmaster'),
        ),
    ]
