# Generated by Django 4.2.7 on 2024-12-03 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0033_slot_attendance_details_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusmaster',
            name='status_value',
        ),
    ]
