# Generated by Django 4.2.7 on 2024-12-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0034_remove_statusmaster_status_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusmaster',
            name='status_type',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
