# Generated by Django 4.2.7 on 2024-12-06 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0036_payment_details'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment_details',
            table='payment_details',
        ),
    ]
