# Generated by Django 4.2.7 on 2024-12-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0038_alter_payment_details_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payoutdetails',
            name='employee_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
