# Generated by Django 4.2.7 on 2024-12-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0039_alter_payoutdetails_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutdetails',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payoutdetails',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
