# Generated by Django 4.2.7 on 2024-12-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0040_payoutdetails_purpose_payoutdetails_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payoutdetails',
            name='reference_id',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
