# Generated by Django 4.2.7 on 2024-12-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0041_alter_payoutdetails_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_details',
            name='api_key',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='payment_details',
            name='secret_key',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
