# Generated by Django 4.2.7 on 2024-12-16 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0062_userslotdetails_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Payroll', '0042_payment_details_api_key_payment_details_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusmaster',
            name='status_description',
            field=models.TextField(blank=True, max_length=550, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeUpdate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.TextField(blank=True, null=True)),
                ('bank_name', models.TextField(blank=True, null=True)),
                ('branch_name', models.TextField(blank=True, null=True)),
                ('account_no', models.TextField(blank=True, null=True)),
                ('account_holder_name', models.TextField(blank=True, null=True)),
                ('ifsc_code', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_company', to='Masters.company_master')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_update',
            },
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.TextField(blank=True, null=True)),
                ('bank_name', models.TextField(blank=True, null=True)),
                ('branch_name', models.TextField(blank=True, null=True)),
                ('account_no', models.TextField(blank=True, null=True)),
                ('account_holder_name', models.TextField(blank=True, null=True)),
                ('ifsc_code', models.TextField(blank=True, null=True)),
                ('initiated_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('utr', models.CharField(blank=True, max_length=100, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_created_by', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_status', to='Payroll.statusmaster')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bank_details',
            },
        ),
    ]
