# Generated by Django 4.2.7 on 2024-12-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0043_statusmaster_status_description_employeeupdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='reference_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
