# Generated by Django 4.2.7 on 2024-12-16 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0062_userslotdetails_status'),
        ('Payroll', '0044_bankdetails_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_company', to='Masters.company_master'),
        ),
        migrations.AlterField(
            model_name='employeeupdate',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_company', to='Masters.company_master'),
        ),
    ]
