# Generated by Django 4.2.7 on 2024-12-16 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0045_bankdetails_company_alter_employeeupdate_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeupdate',
            old_name='company_id',
            new_name='company',
        ),
    ]
