# Generated by Django 4.2.7 on 2024-12-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0050_bankdetailapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetailapi',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
