# Generated by Django 4.2.7 on 2024-12-18 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Payroll', '0051_bankdetailapi_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=255)),
                ('slot_id', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='payslips/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pay_slip_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pay_slip_data',
            },
        ),
    ]
