# Generated by Django 4.2.7 on 2024-12-18 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0062_userslotdetails_status'),
        ('Payroll', '0052_payslip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='slot_id',
            field=models.ForeignKey(db_column='slot_id', on_delete=django.db.models.deletion.CASCADE, related_name='pay_slip_slot_id', to='Masters.slotdetails'),
        ),
    ]
