# Generated by Django 4.2.7 on 2025-01-03 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0063_remove_employee_designation_state_status_and_more'),
        ('Payroll', '0053_alter_payslip_slot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutdetails',
            name='site_id',
            field=models.ForeignKey(blank=True, db_column='site_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payout_site', to='Masters.site_master'),
        ),
        migrations.AlterField(
            model_name='payoutdetails',
            name='company_id',
            field=models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='payout_company', to='Masters.company_master'),
        ),
    ]
