# Generated by Django 5.1.5 on 2025-01-30 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0054_payoutdetails_site_id_alter_payoutdetails_company_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeTaxCalculation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.TextField(blank=True, null=True)),
                ('financial_year', models.TextField(blank=True, null=True)),
                ('total_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('standard_deduction', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_pt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taxable_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_80c', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remaining_taxable_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rebate_under_87a', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('edu_cess', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pending_tax_mount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_tax_paid', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_tax_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_tax_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'income_tax_calculation',
            },
        ),
        migrations.CreateModel(
            name='IncomeTaxMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('financial_year', models.TextField(blank=True, null=True)),
                ('tax_slab_from', models.TextField(blank=True, null=True)),
                ('tax_slab_to', models.TextField(blank=True, null=True)),
                ('tax_rate', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_tax_master_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_tax_master_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'income_tax_master',
            },
        ),
    ]
