# Generated by Django 4.2.7 on 2025-02-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0056_income_tax_parameter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incometaxcalculation',
            name='period',
            field=models.TextField(blank=True, null=True),
        ),
    ]
