# Generated by Django 4.2.7 on 2025-02-05 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0057_incometaxcalculation_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_salary',
            name='tax_parameter',
            field=models.ForeignKey(blank=True, db_column='tax_parameter', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_salary_income_related', to='Payroll.income_tax_parameter'),
        ),
    ]
