# Generated by Django 4.2.7 on 2025-03-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0058_daily_salary_tax_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='incometaxcalculation',
            name='total_gross',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
