# Generated by Django 4.2.7 on 2025-03-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0059_incometaxcalculation_total_gross'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometaxcalculation',
            name='last_tax_paid',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
